version: '3'

services:
  webscraper:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: docker/Dockerfile  # Use the Dockerfile in the current directory
    image: guilhermeolii/webscrapper-pc:latest
    container_name: webscraper
    restart: always
    env_file:
      - docker/docker.env
